# routing segging
## http//localhost:8080/login to http://localhost:7080/auth
## http//localhost:8080/register to http://localhost:7080/register
spring:
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://localhost:7080
          predicates:
            - Path=/login
          filters:
            - SetPath=/auth
        - id: register
          uri: http://localhost:7080
          predicates:
            - Path=/register
