server:
  port: 8080
  servlet:
    session:
      timeout: 60m

logging:
  pattern:
    console: date:%d{yyyy-MM-dd HH:mm:ss}\tthread:%thread\tlevel:%-5level\tlogger:%-48logger{48}\tmessage:%msg%n
    file: date:%d{yyyy-MM-dd HH:mm:ss}\tthread:%thread\tlevel:%-5level\tlogger:%-48logger{48}\tmessage:%msg%n
  config: classpath:logback-spring.xml
  level:
    root: INFO

spring:
  profiles:
    include: >
      routes
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
       fail-on-empty-beans: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: http://localhost:3000
            allowedHeaders: Origin, X-Requested-With, Content-Type, Accept
            allowCredentials: true
            allowedMethods: "*"
